### ISSUE TITLE
Irregual Error Output

### ISSUE THREAD

**Issue by Kannav02** [brokoli777/RefactorCode#1]
It can be seen that sometimes the error is being logged through stderr as displayed in the image below

Image 1
<img width="1175" alt="Screenshot 2024-09-12 at 1 34 03 AM" src="https://github.com/user-attachments/assets/8b83e4df-91ec-4d7f-b4f6-ff031563d13f">

But in most of the independent functions in the file , it is found that rather than being logged, they are being thrown as can be seen in the image below

Image 2
<img width="1095" alt="Screenshot 2024-09-12 at 1 34 12 AM" src="https://github.com/user-attachments/assets/8e32bd2c-a3b8-483f-847b-e27ed017f0a5">

A unified approach of having all of them logged using stderr would be beneficial or maybe throwing all of the errors rather than having some being logged and some being thrown

**Comment by brokoli777** [comment]
Thank you for reporting the issue, the code has been updated to use stderr in all places.
