### ISSUE TITLE
Magic Data For Model Names

### ISSUE THREAD

**Issue by Kannav02** [brokoli777/RefactorCode#2]
Just a suggestion for the following, it could be better to use a constant Map to link the model's name with the Command Line Argument that is being parsed from the user rather than having a temporary data structure as seen in Image 1. 

Image 1
<img width="1018" alt="Screenshot 2024-09-12 at 1 38 33 AM" src="https://github.com/user-attachments/assets/d21741d3-d86f-4c98-b336-9a63c46c0a1f">

This might lead to better support for more models in the future for the language and also provide more code re-use

**Comment by brokoli777** [comment]
Thanks for the suggestion, I made some changes to the model names to make it more dynamic.
