### ISSUE TITLE
Spinner Timing Using Hardcode Value

### ISSUE THREAD

**Issue by Kannav02** [brokoli777/RefactorCode#3]
In the following Code Snippet in the ``` refactorText()``` function, it can be seen that the spinner is using a hardcoded value, this might lead to unnecessary time being used if the AI actually takes less time than 12 seconds

Image 1
<img width="1018" alt="Screenshot 2024-09-12 at 1 45 32 AM" src="https://github.com/user-attachments/assets/8983a919-4d3e-42ee-ab35-d36ea94c47ae">

Can we add the option to start the spinner when the API call is being made and end the spinner when the result is received or return back an error if it doesn't return the output ?

**Comment by brokoli777** [comment]
Thanks for noticing that! I updated the code to stop the spinner once the refactored code is generated.
