### ISSUE TITLE
Adding a -t or a --token option to your RefactorCode

### ISSUE THREAD

**Issue by peterdanwan** [brokoli777/RefactorCode#5]
Hello! I was wondering if it would be possible for me to assist with adding a feature that adds a `-t` or `--token` option for `RefactorCode`.

This option, when used, would output JSON on the user's terminal pertaining to:
1. how many tokens were consumed in their prompt (i.e., `prompt_tokens`)
2. how many tokens were consumed from the AI's response (i.e., `completion_tokens`)
3. how many tokens were consumed in total (i.e., `total_tokens`, the sum of `prompt_tokens` and `completion_tokens`)

I can create a `fork` of your repository such that you will be able to quickly see the changes I make.

**Comment by brokoli777** [comment]
Hey Peter! sorry someone already implemented it for my repo. You could ask on slack who is left.

**Comment by peterdanwan** [comment]
Hi Bregwin, thanks for responding so quickly and letting me know! I'll look on slack for another repository to contribute to.
